[redis_session]
host = ""
password = ""
max_connection_pool = 100

[redis]
host = ""
password = ""

[database_nflow]
driver = "sqlite3"
dsn = "app/app.sqlite"
#driver = "postgres"
#dsn = "postgres://postgres:nflowsecret@localhost:5432/nflow?sslmode=disable"
query="SELECT name,query FROM queries"

[env]
scim_base = "https://localhost:8443"
openid_base = "https://localhost:8443"

[https_engine]
enable = true
cert = "certs/cert.pem"
key = "certs/key.pem"
address = ":9090"
description = "engine"
httpbasic = false

[https_designer]
enable = false
cert = "certs/cert.pem"
key = "certs/key.pem"
address = ":9999"
description = "designer"
httpbasic = true
