[redis]
host =  "localhost:6379"
password = ""


[env]
scim_base="https://localhost:8443"
openid_base="https://localhost:8443"

[https_engine]
enable = true
cert = "certs/cert.pem"
key = "certs/key.pem"
address=":9090"
description="engine"
#user="user"
#password="user"

[https_designer]
enable = false
cert = "certs/cert.pem"
key = "certs/key.pem"
address=":9999"
description="designer"
user="admin"
password="admin"