[redis_session]
host = ""
password = ""
max_connection_pool = 100

[redis]
host = ""
password = ""

[database_nflow]
driver = "sqlite3"
dsn = "app/app.sqlite"
#driver = "postgres"
#dsn = "postgres://postgres:nflowsecret@localhost:5432/nflow?sslmode=disable"
QueryGetToken = "SELECT id, name, token, start, expired, active, header, token_type FROM api_tokens a where  a.name = $1"
QueryGetUser = "SELECT id, username,password,rol, active FROM users WHERE username = $1"
QueryGetApp = "SELECT json , default_js FROM nflow  where name = $1"
QueryGetModules = "SELECT form, mod, code, name FROM modules order by upper(name) desc"
QueryCountModulesByName = "SELECT COUNT(*) c FROM modules WHERE name = $1"
QueryGetModuleByName = "SELECT form, mod, code FROM modules WHERE name = $1"
QueryUpdateModModuleByName = "UPDATE modules SET mod = $1 WHERE name = $2"
QueryUpdateFormModuleByName = "UPDATE modules SET form = $1 WHERE name = $2"
QueryUpdateCodeModuleByName = "UPDATE modules SET code = $1 WHERE name = $2"
QueryUpdateApp = "UPDATE nflow SET json = $1 WHERE name = $2"
QueryInsertModule = "INSERT INTO modules (name, form, mod, code) VALUES ($1,$2,$3, $4)"
QueryDeleteModule = "DELETE FROM modules WHERE name = $1"
QueryInsertLog = "INSERT INTO tracker (log_id, box_id, box_name, box_type, url, username, connection_next, duration, order_box, payload, ip,real_ip,user_agent,query_param,hostname,host) VALUES ($1,$2,$3,$4,$5,$6,$7,$8, $9, $10, $11, $12, $13, $14, $15, $16) "
QueryGetTemplate = "SELECT id, name , content FROM template t  WHERE t.name = $1"
QueryGetTemplateCount = "SELECT  count(*) count  FROM template t WHERE t.name= $1"
QueryGetTemplates = "SELECT id, name, content  FROM template order by name"
QueryUpdateTemplate = "UPDATE template SET content = $1 WHERE name = $2"
QueryInsertTemplate = "INSERT INTO template(content,name) values($1,$2)"

[env]
scim_base = "https://localhost:8443"
openid_base = "https://localhost:8443"

[https_engine]
enable = true
cert = "certs/cert.pem"
key = "certs/key.pem"
address = ":9090"
description = "engine"
httpbasic = false

[https_designer]
enable = false
cert = "certs/cert.pem"
key = "certs/key.pem"
address = ":9999"
description = "designer"
httpbasic = true
